// Sequestered here because they're bulky. Exports at bottom of the file.

const ballGagTable = {
    "a": "n",
    "b": "h",
    "c": "c",
    "d": "n",
    "e": "m",
    "f": "f",
    "g": "g",
    "h": "h",
    "i": "n",
    "j": "n",
    "k": "h",
    "l": "m",
    "m": "m",
    "n": "n",
    "o": "n",
    "p": "p",
    "q": "g",
    "r": "r",
    "s": "ph",
    "t": "ph",
    "u": "n",
    "v": "f",
    "w": "mm",
    "x": "gh",
    "y": "m",
    "z": "ph",
    // NUMBERS
    "0": "phmrn",
    "1": "nnm",
    "2": "phmmn",
    "3": "phhrmm",
    "4": "fnnr",
    "5": "fnfm",
    "6": "phngh",
    "7": "phmfmn",
    "8": "mnghph",
    "9": "nnnm",
    // LIMITED PUNCTUATION
    "\"": "\"",
    "!": "!",
    ".": ".",
    "?": "?",
    ",": ",",
    ":": ":",
    ";": ";",
    " ": " "
}

const muzzleTable = {
    "a": "r",
    "b": "h",
    "c": "c",
    "d": "n",
    "e": "m",
    "f": "h",
    "g": "g",
    "h": "h",
    "i": "n",
    "j": "h",
    "k": "ch",
    "l": "r",
    "m": "m",
    "n": "n",
    "o": "r",
    "p": "h",
    "q": "c",
    "r": "r",
    "s": "h",
    "t": "h",
    "u": "r",
    "v": "h",
    "w": "m",
    "x": "ch",
    "y": "m",
    "z": "h",
    // NUMBERS
    "0": "rnm",
    "1": "hmr",
    "2": "hhrmm",
    "3": "hrrr",
    "4": "hnhm",
    "5": "hnch",
    "6": "hmhmn",
    "7": "mnghh",
    "8": "nnnm",
    "9": "hmn",
    // LIMITED PUNCTUATION
    "\"": "\"",
    "!": "!",
    ".": ".",
    "?": "?",
    ",": ",",
    ":": ":",
    ";": ";",
    " ": " "
}

const ringGagTable = {
    "a": "a",
    "b": "h",
    "c": "c",
    "d": "n",
    "e": "e",
    "f": "h",
    "g": "h",
    "h": "h",
    "i": "i",
    "j": "gh",
    "k": "ch",
    "l": "u",
    "m": "nh",
    "n": "n",
    "o": "o",
    "p": "ch",
    "q": "ch",
    "r": "u",
    "s": "h",
    "t": "gh",
    "u": "u",
    "v": "gh",
    "w": "uu",
    "x": "ch",
    "y": "y",
    "z": "gh",
    // NUMBERS
    "0": "one",
    "1": "ghuuo",
    "2": "ghhuee",
    "3": "houu",
    "4": "highe",
    "5": "hich",
    "6": "heghen",
    "7": "eihhgh",
    "8": "nine",
    "9": "ghen",
    // LIMITED PUNCTUATION
    "\"": "\"",
    "!": "!",
    ".": ".",
    "?": "?",
    ",": ",",
    " ": " "
}

const cockGagTable = {
    "a": "m",
    "b": "mh",
    "c": "mr",
    "d": "uh",
    "e": "m",
    "f": "",
    "g": "gh",
    "h": "hm",
    "i": "m",
    "j": "hu",
    "k": "mn",
    "l": "ml",
    "m": "m",
    "n": "mn",
    "o": "umh",
    "p": "mh",
    "q": "hm",
    "r": "hr",
    "s": "",
    "t": "mh",
    "u": "uh",
    "v": "vf",
    "w": "mhm",
    "x": "",
    "y": "mu",
    "z": "m",
    // NUMBERS
    "0": "mmhrumh",
    "1": "umhmnm",
    "2": "mmhmhmumh",
    "3": "mhhmhrmm",
    "4": "umhuhhr",
    "5": "mvfm",
    "6": "m",
    "7": "mvfmmn",
    "8": "mmghhmmh",
    "9": "mnmmnm",
    // LIMITED PUNCTUATION
    "\"": "\"",
    "!": "!",
    ".": ".",
    "?": "?",
    ",": ",",
    ":": ":",
    ";": ";",
    " ": " "
}

const bitGagTable = {
    "a": "aw",
    "b": "uff",
    "c": "ur",
    "d": "al",
    "e": "uh",
    "f": "fpu",
    "g": "eh",
    "h": "uh",
    "i": "ih",
    "j": "eh",
    "k": "hu",
    "l": "ue",
    "m": "vh",
    "n": "vu",
    "o": "oh",
    "p": "vf",
    "q": "ve",
    "r": "ur",
    "s": "fu",
    "t": "pht",
    "u": "uh",
    "v": "vz",
    "w": "vzz",
    "x": "pff",
    "y": "eu",
    "z": "zu",
    // NUMBERS
    "0": "zuuhuroh",
    "1": "ohvuuh",
    "2": "phtvzzoh",
    "3": "phtuhuruhuh",
    "4": "fpuohuhur",
    "5": "fpuihvzuh",
    "6": "fuihpff",
    "7": "fuuhvzuhvu",
    "8": "uhihehuhpht",
    "9": "vuihvuuh",
    // LIMITED PUNCTUATION
    "\"": "\"",
    "!": "!",
    ".": ".",
    "?": "?",
    ",": ",",
    ":": ":",
    ";": ";",
    " ": " "
}

exports.ballGagTable = ballGagTable
exports.muzzleTable = muzzleTable
exports.ringGagTable = ringGagTable
exports.cockGagTable = cockGagTable
exports.bitGagTable = bitGagTable