// Sequestered here because they're bulky. Exports at bottom of the file.

const ballGagTable = {
    "a": "n",
    "b": "h",
    "c": "c",
    "d": "n",
    "e": "m",
    "f": "f",
    "g": "g",
    "h": "h",
    "i": "n",
    "j": "n",
    "k": "h",
    "l": "m",
    "m": "m",
    "n": "n",
    "o": "n",
    "p": "p",
    "q": "g",
    "r": "r",
    "s": "ph",
    "t": "ph",
    "u": "n",
    "v": "f",
    "w": "mm",
    "x": "gh",
    "y": "m",
    "z": "ph",
    // NUMBERS
    "0": "phmrn",
    "1": "nnm",
    "2": "phmmn",
    "3": "phhrmm",
    "4": "fnnr",
    "5": "fnfm",
    "6": "phngh",
    "7": "phmfmn",
    "8": "mnghph",
    "9": "nnnm",
    // LIMITED PUNCTUATION
    "\"": "\"",
    "!": "!",
    ".": ".",
    "?": "?",
    ",": ",",
    ":": ":",
    ";": ";",
    " ": " "
}
const muzzleTable = {
    "a": "r",
    "b": "h",
    "c": "c",
    "d": "n",
    "e": "m",
    "f": "h",
    "g": "g",
    "h": "h",
    "i": "n",
    "j": "h",
    "k": "ch",
    "l": "r",
    "m": "m",
    "n": "n",
    "o": "r",
    "p": "h",
    "q": "c",
    "r": "r",
    "s": "h",
    "t": "h",
    "u": "r",
    "v": "h",
    "w": "m",
    "x": "ch",
    "y": "m",
    "z": "h",
    // NUMBERS
    "0": "rnm",
    "1": "hmr",
    "2": "hhrmm",
    "3": "hrrr",
    "4": "hnhm",
    "5": "hnch",
    "6": "hmhmn",
    "7": "mnghh",
    "8": "nnnm",
    "9": "hmn",
    // LIMITED PUNCTUATION
    "\"": "\"",
    "!": "!",
    ".": ".",
    "?": "?",
    ",": ",",
    ":": ":",
    ";": ";",
    " ": " "
}
const ringGagTable = {
    "a": "a",
    "b": "h",
    "c": "c",
    "d": "n",
    "e": "e",
    "f": "h",
    "g": "h",
    "h": "h",
    "i": "i",
    "j": "gh",
    "k": "ch",
    "l": "u",
    "m": "nh",
    "n": "n",
    "o": "o",
    "p": "ch",
    "q": "ch",
    "r": "u",
    "s": "h",
    "t": "gh",
    "u": "u",
    "v": "gh",
    "w": "uu",
    "x": "ch",
    "y": "y",
    "z": "gh",
    // NUMBERS
    "0": "one",
    "1": "ghuuo",
    "2": "ghhuee",
    "3": "houu",
    "4": "highe",
    "5": "hich",
    "6": "heghen",
    "7": "eihhgh",
    "8": "nine",
    "9": "ghen",
    // LIMITED PUNCTUATION
    "\"": "\"",
    "!": "!",
    ".": ".",
    "?": "?",
    ",": ",",
    " ": " "
}

exports.ballGagTable = ballGagTable
exports.muzzleTable = muzzleTable
exports.ringGagTable = ringGagTable